### ISSUE TITLE
Curly-brackets have different color

### ISSUE THREAD

**Issue by ghost** [textmate/ruby-haml.tmbundle#11]
%h1{ id: "#{var}"}

Left and right brarces have different color in the example above.

**Comment by infininight** [comment]
Coloring of items is determined by your selected theme, the bundle just defines the scope the items have. So any issue here would be related to the theme not the syntax highlighting.

In this example the braces inside the string are scoped similarly as are the ones outside the string, the two sets are different a bit but so is their usage.
