### ISSUE TITLE
Embedded '#' character in string causes rest of line to be colored as comment

### ISSUE THREAD

**Issue by phatmann** [textmate/ruby-haml.tmbundle#3]
Take this line:

```
= hidden_field :name => "req[locations][#{i}]", :value => location
```

After the '#' character, the remainder of the line is colored like a comment. Very distracting.

**Comment by infininight** [comment]
This works as intended here, are you sure you are using this bundle?

**Comment by tmann-ttc** [comment]
Not a problem with latest version of bundle

**Comment by infininight** [comment]
Thanks.

**Comment by onebree** [comment]
This issue needs to be reopened. Please see #13
