### ISSUE TITLE
Tabs/Soft tabs detection not working well in TM2

### ISSUE THREAD

**Issue by aharpole** [textmate/ruby-haml.tmbundle#5]
My Haml files are all using soft tabs. However, in TextMate 2, the editor detects the document as using tabs.  

I'm not sure if this is an issue with the bundle or with TextMate in general, but since so far it's only a big problem with Haml files, I wanted to try here first.

**Comment by mitnal** [comment]
I don't know if you can change it in the 'Language Grammars' section of the bundle. But you can set it in `.tm_properties`

``` ruby
[ "*.{haml,yml,coffee,feature}" ]
softTabs = true
tabSize = 2
```

See also [this blog post](http://blog.macromates.com/2011/git-style-configuration/) and [this example file](https://github.com/hmans/homedir/blob/master/.tm_properties).

**Comment by aharpole** [comment]
Good to know for now. Hopefully the detection will improve in a later version of TM2 because given that it seemed to work relatively well in TM1 it feels like a regression being forced to edit .tm_properties to get back functionality I had before.  Thanks for the tip!

**Comment by infininight** [comment]
In the current build you can select the proper indent method/size in the bottom bar and it will remember this for the active filetype.
