### ISSUE TITLE
Editing strings screws up alignment

### ISSUE THREAD

**Issue by skorecky** [textmate/ruby-haml.tmbundle#7]
As an example give the following code:

```
- test do
  = link_to "blah", "#"
```

When you attempt to edit a string, in this case either "blah" or "#" it will mess up the alignment and outdent it:

```
- test do
= link_to "blah", "#test"
```

This can become quite a nuance and can causes errors when trying to edit code.

**Comment by skorecky** [comment]
How do you disable indent corrections?

**Comment by infininight** [comment]
It's a preference item, once your bundle updates you can view it to see how it works. Didn't push out the update until just now so you should have it within 24 hours.
